### ISSUE TITLE
Add default image to fallback

### ISSUE THREAD

**Issue by linkrb** [umanit/twig-image-extension#10]
Liip image bundle has a fallback for the images 

https://symfony.com/bundles/LiipImagineBundle/current/configuration.html
`default_image` 

When the path of the image it should use the default_image. 

```
    umanit_image_figure(
      image.path,   // <-  I'm Emtpy = take the fallback 
      'small_thumbnail',
      ['thumbnail', 'large_thumbnail'],
      'image alt',
      'img img--cover img--zoom',
      '(min-width: 768px) 33.3vw, 100vw',
      'class-figure',
      'Figcaption text',
      'class-figcaption',
    )
```

**Comment by DjLeChuck** [comment]
Resolved with the [1.1.1](https://github.com/umanit/twig-image-extension/releases/tag/1.1.1)
