### ISSUE TITLE
Fallback - change the width and height attribute

### ISSUE THREAD

**Issue by linkrb** [umanit/twig-image-extension#9]
Recently [we add the original](https://github.com/umanit/twig-image-extension/issues/7) width and height of the image. 
But it's not ideal. 
Sometimes the original size of the image is very big and the user who deactivates the stylesheet seen a big image. 

The width and the height should take the size of the filter passed to the **src** attribute 

Example : 

```    
umanit_image_figure_lazy_load(
      image.path,
      'small_thumbnail',         <- take the width and the height generated by this filter
      'tiny_thumbnail',
      ['thumbnail', 'large_thumbnail'],
      'image alt',
      'img img--cover img--zoom',
      '(min-width: 768px) 33.3vw, 100vw',
      'class-figure',
      'Figcaption text',
      'class-figcaption',
    )
```    

```
  umanit_image_picture_lazy_load(
    image.path,
    'small_thumbnail',     <- take the width and height generated by this filter
    'tiny_thumbnail',
    ['thumbnail', 'large_thumbnail'],
    {
      (image.path): {
        'media': '(min-width: 768px)',
        'sizes': '(min-width: 1400px) 25vw, 50vw',
        'filters': ['thumbnail', 'large_thumbnail']
      },
      (image2.path): ['thumbnail', 'large_thumbnail']
    },
    'alt img',
    'img img-fluid',
    'class-picture'
  )
```

**Comment by DjLeChuck** [comment]
Done with the [v1.1.0](https://github.com/umanit/twig-image-extension/releases/tag/1.1.0) 👍🏻

**Comment by linkrb** [comment]
This issue add poor performance. Twig image extension generate more images to find the size of images. 

We have to deduce the size of the image and not generate them. 
When the height of the image is not know (with widen of relative resize filter) we can deduce it by a cross product

2000x1200   -> ask widen of 800px -> 1200*800/2000 = 480

I **think** the relative resize do this operation.  The ideal is to find the operation operate by the filter. Or compare this theoretical calculation with real result with the filter.

**Comment by DjLeChuck** [comment]
Fixed in the next version. 👍🏻
